# Generated by Django 4.2.3 on 2023-11-25 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire', models.DateField(null=True)),
                ('type', models.CharField(choices=[('CSH', 'Cash'), ('CRD', 'Card')], max_length=4)),
                ('number', models.PositiveIntegerField(max_length=19, null=True)),
                ('balance', models.BigIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'CRD')), fields=('number', 'holder'), name='unique-card'),
        ),
    ]
