# Generated by Django 4.2.3 on 2024-01-26 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expense', '0003_alter_expense_amount_alter_expense_type_and_more'),
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True)),
                ('amount', models.PositiveIntegerField()),
                ('date', models.DateField(null=True)),
                ('expense', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense.expense')),
                ('income', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='income.income')),
            ],
        ),
    ]
