# Generated by Django 4.2.3 on 2024-01-26 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0009_remove_expense_account'),
        ('income', '0003_remove_income_account'),
        ('transaction', '0002_transactions_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='expense',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense.expense'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='income',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='income.income'),
        ),
    ]
