# Generated by Django 4.2.3 on 2023-11-26 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('GRCRS', 'Groceries'), ('UTLTS', 'Utilities'), ('HLTH', 'Health'), ('TRNPRT', 'Transport'), ('CLTH', 'Clothing'), ('DBT', 'Debt'), ('OTHR', 'Other')], default='OTHR', max_length=6)),
                ('carvable', models.BooleanField(default=False)),
                ('amount', models.PositiveIntegerField(null=True)),
                ('period_start', models.DateField(null=True)),
                ('period_end', models.DateField(null=True)),
                ('recurrence_type', models.CharField(choices=[('YRLY', 'Yearly'), ('MNTH', 'Monthly'), ('WKLY', 'Weekly')], default='MNTH')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True)),
                ('amount', models.PositiveIntegerField()),
                ('expense', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense.expense')),
            ],
        ),
    ]
