# Generated by Django 4.2.3 on 2023-11-26 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('expense', '0001_initial'),
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='income',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='income.income'),
        ),
        migrations.AddField(
            model_name='expense',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.account'),
        ),
    ]
