# Generated by Django 4.2.3 on 2024-01-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('GRCRS', 'Groceries'), ('UTLTS', 'Utilities'), ('HLTH', 'Health'), ('TRNPRT', 'Transport'), ('HOME', 'Home'), ('CLTH', 'Clothing'), ('DBT', 'Debt'), ('GS', 'Gas'), ('OTHR', 'Other')], default='OTHR', max_length=6),
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
