# Generated by Django 4.2.3 on 2024-01-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_alter_expense_amount_alter_expense_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='period_end',
            field=models.DateField(default=None, null=True),
        ),
    ]
