# Generated by Django 4.2.3 on 2024-01-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_alter_expense_period_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='period_end',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
