# Generated by Django 4.2.3 on 2024-01-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_alter_expense_period_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
