# Generated by Django 4.2.3 on 2024-01-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_alter_expense_period_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
