# Generated by Django 4.2.3 on 2024-01-26 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0008_expense_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='account',
        ),
    ]
