# Generated by Django 4.2.3 on 2023-11-26 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('amount', models.PositiveIntegerField(null=True)),
                ('period_start', models.DateField(null=True)),
                ('period_end', models.DateField(null=True)),
                ('type', models.CharField(choices=[('YRLY', 'Yearly'), ('MNTH', 'Monthly'), ('WKLY', 'Weekly')])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
        ),
    ]
