# Generated by Django 4.2.3 on 2024-01-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
