# Generated by Django 4.2.3 on 2024-01-26 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_alter_income_period_end_alter_income_period_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='account',
        ),
    ]
