name: Continious Integration

on:
  workflow_dispatch:
  workflow_run: 
    workflows: ["Lint Code Base"]
    types:
      - completed
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  tests:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     python-version: []
    env:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_HOST: localhost
        POSTGRES_DB: postgres
        POSTGRES_PORT: 5432
    services:
        postgres_main:
            image: postgres
            env:
                POSTGRES_USER: ${{ env.POSTGRES_USER }}
                POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
                POSTGRES_DB: ${{ env.POSTGRES_DB }}
            ports:
                - 5432:5432
            options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
        cache: 'pip'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env:
        DEBUG: "0"
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        DB_USERNAME: ${{ env.POSTGRES_USER }}
        DB_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        DB_HOST: ${{ env.POSTGRES_HOST }}
        DB_DATABASE: ${{ env.POSTGRES_DB }}
        DB_PORT: ${{ env.POSTGRES_PORT }}
      run: |
        python manage.py test
